### ISSUE TITLE
Retarget ends up blocking without a debug probe

### ISSUE THREAD

**Issue by arskanov** [0x6d61726b/mbed-os-retarget-segger-rtt#1]
Hi, and thanks for taking the time to create this.

Just a heads up for anyone using this: I ran into an issue where the implementation blocked on a full buffer, with no debug probe attached, on default settings. This was due to the line https://github.com/0x6d61726b/mbed-os-retarget-segger-rtt/blob/648b5440bd2744c5356c73b9bfdf8081ca65d79a/SeggerRTT/SEGGER_RTT_Conf.h#L91

The whole thing becomes non-blocking if that line is uncommented. Perhaps a non-blocking default option would be safer?

**Comment by 0x6d61726b** [comment]
Hello arskanov,

thanks a lot for your comment. I have submitted the [mbed-os-retarget-segger-rtt](https://os.mbed.com/users/0x6d61726b/code/mbed-os-retarget-segger-rtt/) library at a different place.

The default option for the latest SEGGER_RTT version 6.44i is defined in SEGGER_RTT.c and has the value `SEGGER_RTT_MODE_NO_BLOCK_SKIP` that should not lead to any blocking when the debugger is not connected.
